name: Build and Release

on:
  push:
    branches:
      - deploy-ego

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    container:
      image: fedora:43
    defaults:
      run:
        shell: bash

    steps:
      # Install basic deps (git needs to be installed before checking out the repo!)
      - name: Install basic dependencies
        run: |
          dnf install -y git glib2-devel  

      # Check out code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0      # fetch all history
          fetch-tags: true    # fetch tags

      # Install Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Check if release for this version already exists
      - name: Check for existing release
        id: check_release
        run: |
          VERSION=$(node -p "require('./src/metadata.json')['version-name']")
          EXISTING=$(git ls-remote --tags origin "v$VERSION" | awk '{print $2}' | sed 's|refs/tags/||' || true)
          if [ -n "$EXISTING" ]; then
            echo "Tag v$VERSION already exists. Failing."
            exit 1
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Install GNOME Shell
      - name: Install GNOME Shell
        run: |
          dnf install -y gnome-shell

      # Install dependencies
      - name: Install npm dependencies
        run: npm ci

      # Build
      - run: npm run build:release

      # Locate .zip file:
      - name: Locate .zip
        id: locate_zip
        run: |
          source tools/config.sh
          shopt -s nullglob
          ZIPFILES=("$distDir"/*.zip)
          [[ ${#ZIPFILES[@]} -gt 0 ]] || { echo "zip file not present in $distDir"; exit 1; }
          ZIPFILE="${ZIPFILES[0]}"
          echo "ZIPFILE=$ZIPFILE" >> $GITHUB_ENV

      # Upload zip as an artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.ZIPFILE }}

      # Create the GitHub release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          body: "Release for version ${{ env.VERSION }}"
          draft: false
          prerelease: false
          files: |
            ${{ env.ZIPFILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload to extensions.gnome.org
      - name: Upload to EGO
        run: |
            gnome-extensions upload --user $USERNAME --password $PASSWORD $ZIPFILE
        env:
          USERNAME: ${{ secrets.EGO_USER }}
          PASSWORD: ${{ secrets.EGO_PASSWORD }}
